lib: [
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/META" {"META"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/dune-package" {"dune-package"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/IrminTest.a" {"lib/IrminTest.a"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/IrminTest.cma" {"lib/IrminTest.cma"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/IrminTest.cmxa" {"lib/IrminTest.cmxa"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/IrminTest.cmxs" {"lib/IrminTest.cmxs"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/irminTest.cmi" {"lib/irminTest.cmi"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/irminTest.cmt" {"lib/irminTest.cmt"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/irminTest.cmx" {"lib/irminTest.cmx"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/lib/irminTest.ml" {"lib/irminTest.ml"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/lib/irmin-test/opam" {"opam"}
]
bin: [
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/bin/IrminTestApp.exe" {"IrminTestApp.exe"}
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/bin/TestIrminTest.exe" {"TestIrminTest.exe"}
]
doc: [
  "/home/aweis/irmin-indexeddb/_esy/default/store/b/irmin_test-7e857114/install/default/doc/irmin-test/README.md"
]
